# vim: set foldmarker={{{,}}} foldmethod=marker:

# include dark.conf
include light.conf

font_family Rec Mono Duotone

allow_remote_control yes

term xterm-256color

copy_on_select yes

enable_audio_bell no

tab_bar_edge top
tab_title_template {index}: {title}

map kitty_mod+t new_tab_with_cwd
map shift+right next_tab
map shift+left previous_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
